type AggrandizementPropertyName = (
  '# of Ratings (This Version)'
  | '# of Ratings'
  | 'Album Artist'
  | 'Album Artwork'
  | 'Album Track #'
  | 'Album'
  | 'Altitude'
  | 'Artist'
  | 'Artwork URL'
  | 'Artwork'
  | 'Author'
  | 'Birthday'
  | 'Camera Make'
  | 'Camera Model'
  | 'Category'
  | 'City'
  | 'Comments'
  | 'Company'
  | 'Composer'
  | 'Contact Photo'
  | 'Content Rating'
  | 'Country'
  | 'Creation Date'
  | 'Currency Code'
  | 'Date Added'
  | 'Date Taken'
  | 'Department'
  | 'Description'
  | 'Disc #'
  | 'Download Size'
  | 'Duration'
  | 'Email Address'
  | 'Excerpt'
  | 'File Extension'
  | 'File Size'
  | 'First Name'
  | 'Formatted Price'
  | 'Frame Rate'
  | 'Genre'
  | 'Group'
  | 'Has Album Artwork'
  | 'Has Photo'
  | 'Height'
  | 'iPad Screenshot URLs'
  | 'Is a Screenshot'
  | 'Is Cloud Item'
  | 'Is Explicit'
  | 'Is Favorite'
  | 'Is Hidden'
  | 'Is Universal'
  | 'Job Title'
  | 'Keys'
  | 'Last Modified Date'
  | 'Last Name'
  | 'Last Played Date'
  | 'Last Updated'
  | 'Latitude'
  | 'Location'
  | 'Longitude'
  | 'Lyrics'
  | 'Main Image URL'
  | 'Media Kind'
  | 'Media Type'
  | 'Metadata Dictionary'
  | 'Middle Name'
  | 'Minimum OS Version'
  | 'Name'
  | 'Nickname'
  | 'Notes'
  | 'Number of Words'
  | 'Orientation'
  | 'Page Contents'
  | 'Page Selection'
  | 'Page URL'
  | 'Phone Number'
  | 'Phonetic First Name'
  | 'Phonetic Last Name'
  | 'Phonetic Middle Name'
  | 'Photo Type'
  | 'Play Count'
  | 'Prefix'
  | 'Price'
  | 'Published Date'
  | 'Rating (This Version)'
  | 'Rating'
  | 'Release Date'
  | 'Release Notes'
  | 'Screenshot URLs'
  | 'Skip Count'
  | 'State'
  | 'Store ID'
  | 'Store URL'
  | 'Streamable'
  | 'Street Address'
  | 'Street'
  | 'Suffix'
  | 'Supported Devices'
  | 'Supported Languages'
  | 'Supports Game Center'
  | 'Time Taken'
  | 'Title'
  | 'URL'
  | 'Values'
  | 'Version'
  | 'Width'
  | 'ZIP Code'
);

export default AggrandizementPropertyName;
