type WFWorkflowActionIdentifier = (
  'is.workflow.actions.ask'
  | 'is.workflow.actions.airplanemode.set'
  | 'is.workflow.actions.choosefrommenu'
  | 'is.workflow.actions.comment'
  | 'is.workflow.actions.conditional'
  | 'is.workflow.actions.count'
  | 'is.workflow.actions.delay'
  | 'is.workflow.actions.downloadurl'
  | 'is.workflow.actions.flashlight'
  | 'is.workflow.actions.getitemname'
  | 'is.workflow.actions.getitemtype'
  | 'is.workflow.actions.gettext'
  | 'is.workflow.actions.getbatterylevel'
  | 'is.workflow.actions.getvalueforkey'
  | 'is.workflow.actions.lowpowermode.set'
  | 'is.workflow.actions.math'
  | 'is.workflow.actions.number'
  | 'is.workflow.actions.nothing'
  | 'is.workflow.actions.runworkflow'
  | 'is.workflow.actions.setbrightness'
  | 'is.workflow.actions.setitemname'
  | 'is.workflow.actions.setvariable'
  | 'is.workflow.actions.showresult'
  | 'is.workflow.actions.url'
  | 'is.workflow.actions.viewresult'
);

export default WFWorkflowActionIdentifier;
