type WFWorkflowActionIdentifier = (
  'is.workflow.actions.appendvariable'
  | 'is.workflow.actions.airplanemode.set'
  | 'is.workflow.actions.ask'
  | 'is.workflow.actions.bluetooth.set'
  | 'is.workflow.actions.cellulardata.set'
  | 'is.workflow.actions.choosefrommenu'
  | 'is.workflow.actions.comment'
  | 'is.workflow.actions.conditional'
  | 'is.workflow.actions.count'
  | 'is.workflow.actions.delay'
  | 'is.workflow.actions.downloadurl'
  | 'is.workflow.actions.exit'
  | 'is.workflow.actions.flashlight'
  | 'is.workflow.actions.getbatterylevel'
  | 'is.workflow.actions.getipaddress'
  | 'is.workflow.actions.getitemname'
  | 'is.workflow.actions.getitemtype'
  | 'is.workflow.actions.gettext'
  | 'is.workflow.actions.getvalueforkey'
  | 'is.workflow.actions.getvariable'
  | 'is.workflow.actions.getwifi'
  | 'is.workflow.actions.handoff'
  | 'is.workflow.actions.lowpowermode.set'
  | 'is.workflow.actions.math'
  | 'is.workflow.actions.nothing'
  | 'is.workflow.actions.number'
  | 'is.workflow.actions.runsshscript'
  | 'is.workflow.actions.runworkflow'
  | 'is.workflow.actions.setbrightness'
  | 'is.workflow.actions.setitemname'
  | 'is.workflow.actions.setvariable'
  | 'is.workflow.actions.showresult'
  | 'is.workflow.actions.url'
  | 'is.workflow.actions.vibrate'
  | 'is.workflow.actions.viewresult'
  | 'is.workflow.actions.waittoreturn'
  | 'is.workflow.actions.wifi.set'
);

export default WFWorkflowActionIdentifier;
